### ISSUE TITLE
spring mvc @Tcc注解不可用

### ISSUE THREAD

**Issue by jilonghun** [yu199195/hmily#34]
背景：
1、按这个：https://github.com/yu199195/hmily/wiki/Dubbo-User-Guide 要求进行配置完成；
2、项目框架是spring MVC（4.3.7），dubbo（2.5.6）；

问题：
1、没有报错信息，进不了@Tcc表示的方法，service的句柄正常，但是最后报的是空指针，如果去掉@Tcc注解就可以使用
2、AOP已经生效：

![image](https://user-images.githubusercontent.com/13517592/44514928-dd029d80-a6f3-11e8-8233-62ff07178a7d.png)

![image](https://user-images.githubusercontent.com/13517592/44514182-015d7a80-a6f2-11e8-9939-503fdd0bee84.png)

![image](https://user-images.githubusercontent.com/13517592/44560697-8ba1ef00-a783-11e8-89be-4518944adede.png)

**Comment by yu199195** [comment]
cxfcontent 为空，检查下，配置启动项，看看

**Comment by jilonghun** [comment]
HmilyTransactionBootstrap启动对象，怎么配置都不加载，是什么情况

**Comment by yu199195** [comment]
他就是spring 的一个bean 看下demo 有xml 方式 yml 配置方式， 有springboot starter 方式

**Comment by jilonghun** [comment]
问题原因已经找到，这个是由于bean的加载方式导致的，我配置的是延迟初始化，配置成启动时加载即可。

**Comment by yu199195** [comment]
good
