### ISSUE TITLE
超时异常是怎么处理？

### ISSUE THREAD

**Issue by 654894017** [yu199195/hmily#75]
1.看到代码在异常时未判断是超时异常或者乐观锁异常。直接进行cancel处理，有可能被调用方的try方法还在执行的情况。这样不是会有问题？

**Comment by yu199195** [comment]
超时是通过自己的的定时任务回滚，超时也是异常，框架不会调用他的cancel方法，这个你知道?

**Comment by yu199195** [comment]
调用过程中，会形成一个调用链，自身的异常，依赖自身的事务去回滚，当一个节点异常的时候，框架会调用其他调用过的节点rpc的 cancel方法。并不会调用自身异常的节点

**Comment by 654894017** [comment]
> 用其他调用过的节点rpc的 cancel方法。并不会调用自身异常的节点

明白了，感谢感谢   哈哈哈哈
