### ISSUE TITLE
主动方调用被动方，被动方入库之后模拟异常，将导致被动方cancel不被调用

### ISSUE THREAD

**Issue by tlhhup** [yu199195/hmily#84]
HmilyFeignHandler中调用被动方业务和存储被动方的事务信息是否需要对调一下。
try {
                final HmilyTransactionContext hmilyTransactionContext = HmilyTransactionContextLocal.getInstance().get();
                if (Objects.nonNull(hmilyTransactionContext)) {
                    if (hmilyTransactionContext.getRole() == HmilyRoleEnum.LOCAL.getCode()) {
                        hmilyTransactionContext.setRole(HmilyRoleEnum.INLINE.getCode());
                    }
                }
                final HmilyTransactionExecutor hmilyTransactionExecutor =
                        SpringBeanUtils.getInstance().getBean(HmilyTransactionExecutor.class);
                //先存储被动方的事务信息
                final HmilyParticipant hmilyParticipant = buildParticipant(hmily, method, args, hmilyTransactionContext);
                if (hmilyTransactionContext.getRole() == HmilyRoleEnum.INLINE.getCode()) {
                    hmilyTransactionExecutor.registerByNested(hmilyTransactionContext.getTransId(),
                            hmilyParticipant);
                } else {
                    hmilyTransactionExecutor.enlistParticipant(hmilyParticipant);
                }
               //再调用被动方业务
                final Object invoke = this.handlers.get(method).invoke(args);
                return invoke;
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                throw throwable;
            }

**Comment by yu199195** [comment]
你的业务场景是什么样的，是怎么进行调用的。 被动方，异常了， 只会调用 之前节点的cancel  或者 你的被动方，本地自己加上事务。 他自身异常了，是不会走cancel的，自身异常了，代表自己执行不成功，就不需要走cancel了，不知道明白了吗？

**Comment by tlhhup** [comment]
有个需求是主动方保存数据需要依赖被动方返回的数据，现在使用的时候发现被动方入库之后抛异常主动方回执行cancel但是被动方不会执行

**Comment by yu199195** [comment]
被动方异常了，自己去回滚，还需要调用cancel干嘛，自己异常了，还要调用自己的cancel 本地事务解决即可
